line-length = 88
indent-width = 4
target-version = "py311"

[lint]
select = [
    "E4",
    "E7",
    "E9",
    "F"
]
ignore = ["E402"]

[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
order-by-type = true

[format]
docstring-code-format = true
docstring-code-line-length = 72
